services:
  firebase_authentication.extractor.bearer:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\JWTExtractor\BearerExtractor

  firebase_authentication.extractor.cookie:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\JWTExtractor\CookieExtractor
    arguments:
      $cookieName: '%firebase_authentication.cookie_name%'

  firebase_authentication.public_key_fetcher:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\PublicKeyFetcher
    abstract: true
    autowire: true

  firebase_authentication.jws_validator:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\RS256JWSValidator
    abstract: true
    arguments:
      $firebaseProjectId: '%firebase_authentication.project_id%'
      $userIdentifier: '%firebase_authentication.user_identifier%'

  firebase_authentication.authenticator:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Security\FirebaseAuthenticator
    abstract: true

  firebase_authentication.user_provider:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Security\UserProvider
