services:
  _defaults:
    autowire: true

  DanieleAmbrosino\FirebaseAuthenticationBundle\Contracts\JWTExtractorInterface:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\JWTExtractor
  
  DanieleAmbrosino\FirebaseAuthenticationBundle\Contracts\PublicKeyFetcherInterface:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\PublicKeyFetcher
  
  DanieleAmbrosino\FirebaseAuthenticationBundle\Contracts\JWSValidatorInterface:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\RS256JWSValidator
    arguments:
      - '%firebase_authentication.project_id%'
  
  firebase_authentication.authenticator:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Security\FirebaseAuthenticator
