services:
  firebase_authentication.extractor.bearer:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\JWTExtractor\BearerExtractor

  firebase_authentication.extractor.cookie:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\JWTExtractor\CookieExtractor
    arguments:
      $cookieName: '%firebase_authentication.cookie_name%'

  firebase_authentication.public_key_fetcher:
    abstract: true
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\PublicKeyFetcher
    autowire: true

  firebase_authentication.jws_validator:
    abstract: true
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\RS256JWSValidator
    arguments:
      $firebaseProjectId: '%firebase_authentication.project_id%'

  firebase_authentication.authenticator:
    abstract: true
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Security\FirebaseAuthenticator

  firebase_authentication.user_provider:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Security\UserProvider
