services:
  firebase_authentication.extractor.bearer:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\JWTExtractor\BearerExtractor

  firebase_authentication.extractor.cookie:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\JWTExtractor\CookieExtractor
    arguments:
      $cookieName: '%firebase_authentication.cookie_name%'

  firebase_authentication.public_key_fetcher:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\PublicKeyFetcher
    autowire: true
    arguments:
      $strategy: '%firebase_authentication.extractor%'

  firebase_authentication.jws_validator:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Services\RS256JWSValidator
    arguments:
      $firebaseProjectId: '%firebase_authentication.project_id%'
      $strategy: '%firebase_authentication.extractor%'

  firebase_authentication.authenticator:
    class: DanieleAmbrosino\FirebaseAuthenticationBundle\Security\FirebaseAuthenticator
    arguments:
      $publicKeyFetcher: '@firebase_authentication.public_key_fetcher'
      $jwsValidator: '@firebase_authentication.jws_validator'
